version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/nft-market
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install NPM packages
          command: npm ci
      - run:
          name: Run tests
          command: npm t
      - save_cache:
          paths:
            - ~/nft-market/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
